recursive = true
exclude = [
    ".github",
]
manifest_file = [
    "argtable3/.build-test-rules.yml",
    "bdc_motor/.build-test-rules.yml",
    "ccomp_timer/.build-test-rules.yml",
    "coremark/.build-test-rules.yml",
    "esp_daylight/.build-test-rules.yml",
    "esp_cli_commands/.build-test-rules.yml",
    "esp_encrypted_img/.build-test-rules.yml",
    "esp_flash_dispatcher/.build-test-rules.yml",
    "esp_gcov/.build-test-rules.yml",
    "esp_jpeg/.build-test-rules.yml",
    "esp_linenoise/.build-test-rules.yml",
    "esp_schedule/.build-test-rules.yml",
    "esp_cli/.build-test-rules.yml",
    "esp_serial_slave_link/.build-test-rules.yml",
    "expat/.build-test-rules.yml",
    "iqmath/.build-test-rules.yml",
    "esp_isotp/.build-test-rules.yml",
    "jsmn/.build-test-rules.yml",
    "json_generator/.build-test-rules.yml",
    "json_parser/.build-test-rules.yml",
    "libpng/.build-test-rules.yml",
    "libsodium/.build-test-rules.yml",
    "onewire_bus/.build-test-rules.yml",
    "pcap/.build-test-rules.yml",
    "pid_ctrl/.build-test-rules.yml",
    "qrcode/.build-test-rules.yml",
    "quirc/.build-test-rules.yml",
    "thorvg/.build-test-rules.yml",
    "touch_element/.build-test-rules.yml",
    "zlib/.build-test-rules.yml",
    "libjpeg-turbo/.build-test-rules.yml",
    ".build-test-rules.yml",
]
check_warnings = true

# build related options
build_dir = "build_@t_@w"
config = "sdkconfig.ci"
ignore_warning_file = ".ignore_build_warnings.txt"
