name: Run clang-tidy

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    name: Run clang-tidy
    runs-on: ubuntu-24.04
    container: espressif/idf:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install esp-clang
        run: |
          ${IDF_PATH}/tools/idf_tools.py --non-interactive install esp-clang
      - name: Install clang-tidy-sarif
        run: |
          curl -sSL https://github.com/psastras/sarif-rs/releases/download/clang-tidy-sarif-v0.8.0/clang-tidy-sarif-x86_64-unknown-linux-gnu -o clang-tidy-sarif
          chmod +x clang-tidy-sarif
      - name: Install pyclang
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install pyclang~=0.2.0
      - name: Run code analysis
        shell: bash
        env:
          IDF_TOOLCHAIN: clang
          IDF_TARGET: esp32
        working-directory: .github/clang-tidy/test_app
        run: |
          . ${IDF_PATH}/export.sh
          idf.py reconfigure
          idf.py clang-check @build/clang_check_args --run-clang-tidy-py run-clang-tidy
          cp warnings.txt ${GITHUB_WORKSPACE}/warnings.txt
      - name: Convert clang-tidy results into SARIF output
        run: |
          export PATH=$PWD:$PATH
          ./clang-tidy-sarif -o results.sarif.raw -i warnings.txt
          # Remove warnings which recommend using functions not supported in newlib.
          python3 $GITHUB_WORKSPACE/.github/filter_sarif.py -o results.sarif \
            --include-prefix ${GITHUB_WORKSPACE}/ \
            --exclude-text-contains memset_s \
            --exclude-text-contains memmove_s \
            --exclude-text-contains memcpy_s \
            --exclude-text-contains fprintf_s \
            --exclude-text-contains snprintf_s \
            --exclude-text-contains strncpy_s \
            --exclude-text-contains sscanf_s \
            results.sarif.raw
      - uses: actions/upload-artifact@v4
        with:
          path: |
            warnings.txt
            results.sarif
            results.sarif.raw
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: clang-tidy
