name: Build and Deploy Programming Guides

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mdBook ğŸ“¥
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Install doxygen tools ğŸ§±
        run: |-
          sudo apt-get install -y doxygen
          pip install esp-doxybook

      - name: Build docs ğŸ”§
        run: |
          version="latest"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          version="pr-preview-${{ github.event.pull_request.number }}"
          fi
          python3 ./.github/build_docs.py --version "$version" --output-dir "docs_build_output"

      - name: Check Links ğŸ”
        uses: lycheeverse/lychee-action@v2
        with:
          # Check links in docs_build_output
          args: >-
            --no-progress
            --include-fragments
            --root-dir docs_build_output
            --exclude-path '.*/404\.html$'
            docs_build_output/**/*.html
          # Fail the action if broken links are found
          fail: true

      # Create directory structure for GitHub Pages with "version prefix"
      - name: Prepare files for deployment ğŸ“
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          version="latest"
          mkdir -p "gh-pages/$version"
          cp -r docs_build_output/* "gh-pages/$version/"

      - name: Upload Pages artifact ğŸ“¤
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}latest/
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages ğŸ“¥
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4
